INSERT INTO books (id, characteristic, description, image, name, price, author_id, publishing_id)
VALUES (1, 'sadfrwas', 'asdfgsadf', '/Photos/Latin_dictionary.jpg', 'Aboba', 156, null, null),
       (2, 'sadfrwas', 'asdfgsadf', '/Photos/Latin_dictionary.jpg', 'Aboba', 156, null, null),
       (3, 'sadfrwas', 'asdfgsadf', '/Photos/Latin_dictionary.jpg', 'Aboba', 156, null, null),
       (4, 'sadfrwas', 'asdfgsadf', '/Photos/Latin_dictionary.jpg', 'Aboba', 156, null, null),
       (5, 'sadfrwas', 'asdfgsadf', '/Photos/Latin_dictionary.jpg', 'Aboba', 156, null, null),
       (6, 'sadfrwas', 'asdfgsadf', '/Photos/Latin_dictionary.jpg', 'Aboba', 156, null, null),
       (7, 'sadfrwas', 'asdfgsadf', '/Photos/Latin_dictionary.jpg', 'Aboba', 156, null, null),
       (8, 'sadfrwas', 'asdfgsadf', '/Photos/Latin_dictionary.jpg', 'Aboba', 156, null, null),
       (9, 'sadfrwas', 'asdfgsadf', '/Photos/Latin_dictionary.jpg', 'Aboba', 156, null, null),
       (10, 'sadfrwas', 'asdfgsadf', '/Photos/Latin_dictionary.jpg', 'Aboba', 156, null, null),
       (11, 'sadfrwas', 'asdfgsadf', '/Photos/Latin_dictionary.jpg', 'Aboba', 156, null, null),
       (12, 'sadfrwas', 'asdfgsadf', '/Photos/Latin_dictionary.jpg', 'Aboba', 156, null, null),
       (13, 'sadfrwas', 'asdfgsadf', '/Photos/Latin_dictionary.jpg', 'Aboba', 156, null, null),
       (14, 'sadfrwas', 'asdfgsadf', '/Photos/Latin_dictionary.jpg', 'Aboba', 156, null, null),
       (15, 'sadfrwas', 'asdfgsadf', '/Photos/Latin_dictionary.jpg', 'Aboba', 156, null, null),
       (16, 'sadfrwas', 'asdfgsadf', '/Photos/Latin_dictionary.jpg', 'Aboba', 156, null, null),
       (17, 'sadfrwas', 'asdfgsadf', '/Photos/Latin_dictionary.jpg', 'Aboba', 156, null, null),
       (18, 'sadfrwas', 'asdfgsadf', '/Photos/Latin_dictionary.jpg', 'Aboba', 156, null, null),
       (19, 'sadfrwas', 'asdfgsadf', '/Photos/Latin_dictionary.jpg', 'Aboba', 156, null, null),
       (20, 'sadfrwas', 'asdfgsadf', '/Photos/Latin_dictionary.jpg', 'Aboba', 156, null, null),
       (21, 'sadfrwas', 'asdfgsadf', '/Photos/Latin_dictionary.jpg', 'Aboba', 156, null, null),
       (22, 'sadfrwas', 'asdfgsadf', '/Photos/Latin_dictionary.jpg', 'Aboba', 156, null, null),
       (23, 'sadfrwas', 'asdfgsadf', '/Photos/Latin_dictionary.jpg', 'Aboba', 156, null, null),
       (24, 'sadfrwas', 'asdfgsadf', '/Photos/Latin_dictionary.jpg', 'Aboba', 156, null, null),
       (25, 'sadfrwas', 'asdfgsadf', '/Photos/Latin_dictionary.jpg', 'Aboba', 156, null, null),
       (26, 'sadfrwas', 'asdfgsadf', '/Photos/Latin_dictionary.jpg', 'Aboba', 156, null, null),
       (27, 'sadfrwas', 'asdfgsadf', '/Photos/Latin_dictionary.jpg', 'Aboba', 156, null, null);

ALTER SEQUENCE book_seq RESTART WITH 28;