INSERT INTO books (id, characteristic, description, english_name, image, name, price, sales_amount, shop_amount, author_id, publishing_id)
VALUES (1, 'sadfrwas', 'asdfgsadf', 'Aboba', '/Photos/Latin_dictionary.jpg', 'Aboba', 156, 500, 0, 1, null),
       (2, 'sadfrwas', 'asdfgsadf', 'Aboba', '/Photos/Latin_dictionary.jpg', 'Aboba', 156, 500, 786, 2, null),
       (3, 'sadfrwas', 'asdfgsadf', 'Aboba', '/Photos/Latin_dictionary.jpg', 'Aboba', 156, 500, 0, 3, null),
       (4, 'sadfrwas', 'asdfgsadf', 'Aboba', '/Photos/Latin_dictionary.jpg', 'Aboba', 156, 500, 786, 4, null),
       (5, 'sadfrwas', 'asdfgsadf', 'Aboba', '/Photos/Latin_dictionary.jpg', 'Aboba', 156, 500, 786, 5, null),
       (6, 'sadfrwas', 'asdfgsadf', 'Aboba', '/Photos/Latin_dictionary.jpg', 'Aboba', 156, 500, 786, 6, null),
       (7, 'sadfrwas', 'asdfgsadf', 'Aboba', '/Photos/Latin_dictionary.jpg', 'Aboba', 156, 500, 786, 7, null),
       (8, 'sadfrwas', 'asdfgsadf', 'Aboba', '/Photos/Latin_dictionary.jpg', 'Aboba', 156, 500, 0, 5, null),
       (9, 'sadfrwas', 'asdfgsadf', 'Aboba', '/Photos/Latin_dictionary.jpg', 'Aboba', 156, 500, 786, 5, null),
       (10, 'sadfrwas', 'asdfgsadf', 'Aboba', '/Photos/Latin_dictionary.jpg', 'Aboba', 156, 500, 786, 2, null),
       (11, 'sadfrwas', 'asdfgsadf', 'Aboba', '/Photos/Latin_dictionary.jpg', 'Aboba', 156, 500, 786, 1, null),
       (12, 'sadfrwas', 'asdfgsadf', 'Aboba', '/Photos/Latin_dictionary.jpg', 'Aboba', 156, 500, 786, 3, null),
       (13, 'sadfrwas', 'asdfgsadf', 'Aboba', '/Photos/Latin_dictionary.jpg', 'Aboba', 156, 500, 0, 7, null),
       (14, 'sadfrwas', 'asdfgsadf', 'Aboba', '/Photos/Latin_dictionary.jpg', 'Aboba', 156, 500, 786, 6, null),
       (15, 'sadfrwas', 'asdfgsadf', 'Aboba', '/Photos/Latin_dictionary.jpg', 'Aboba', 156, 500, 0, 3, null),
       (16, 'sadfrwas', 'asdfgsadf', 'Aboba', '/Photos/Latin_dictionary.jpg', 'Aboba', 156, 500, 786, 6, null),
       (17, 'sadfrwas', 'asdfgsadf', 'Aboba', '/Photos/Latin_dictionary.jpg', 'Aboba', 156, 500, 0, 2, null),
       (18, 'sadfrwas', 'asdfgsadf', 'Aboba', '/Photos/Latin_dictionary.jpg', 'Aboba', 156, 500, 0, 7, null),
       (19, 'sadfrwas', 'asdfgsadf', 'Aboba', '/Photos/Latin_dictionary.jpg', 'Aboba', 156, 500, 786, 2, null),
       (20, 'sadfrwas', 'asdfgsadf', 'Aboba', '/Photos/Latin_dictionary.jpg', 'Aboba', 156, 500, 786, 6, null),
       (21, 'sadfrwas', 'asdfgsadf', 'Aboba', '/Photos/Latin_dictionary.jpg', 'Aboba', 156, 500, 786, 4, null),
       (22, 'sadfrwas', 'asdfgsadf', 'Aboba', '/Photos/Latin_dictionary.jpg', 'Aboba', 156, 500, 786, 4, null),
       (23, 'sadfrwas', 'asdfgsadf', 'Aboba', '/Photos/Latin_dictionary.jpg', 'Aboba', 156, 500, 786, 1, null),
       (24, 'sadfrwas', 'asdfgsadf', 'Aboba', '/Photos/Latin_dictionary.jpg', 'Aboba', 156, 500, 786, 2, null),
       (25, 'sadfrwas', 'asdfgsadf', 'Aboba', '/Photos/Latin_dictionary.jpg', 'Aboba', 156, 500, 786, 3, null),
       (26, 'sadfrwas', 'asdfgsadf', 'Aboba', '/Photos/Latin_dictionary.jpg', 'Aboba', 156, 500, 786, 1, null),
       (27, 'sadfrwas', 'asdfgsadf', 'Aboba', '/Photos/Latin_dictionary.jpg', 'Aboba', 156, 500, 0, 4, null);

ALTER SEQUENCE book_seq RESTART WITH 28;